/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Matrix */

#ifndef _Included_Matrix
#define _Included_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Matrix
 * Method:    multiplyNative
 * Signature: ([D[D[DIII)V
 */
JNIEXPORT void JNICALL Java_Matrix_multiplyNative
  (JNIEnv * env, jobject, jdoubleArray m1, jdoubleArray m2, jdoubleArray result, jint m1_cols, jint m2_cols, jint result_rows);

/*
 * Class:     Matrix
 * Method:    powerNative
 * Signature: ([D[DIII)V
 */
JNIEXPORT void JNICALL Java_Matrix_powerNative
  (JNIEnv * env, jobject, jdoubleArray m, jdoubleArray result, jint m_cols, jint exp);

#ifdef __cplusplus
}
#endif
#endif
